// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Currency struct {
	ID            int32
	Code          string
	Name          string
	DecimalPlaces int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ExchangeRate struct {
	BaseCurrencyID int32
	CurrencyID     int32
	ExchangeRate   pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ExchangeRateHistory struct {
	ID             int32
	BaseCurrencyID int32
	CurrencyID     int32
	ExchangeRate   pgtype.Numeric
	Timestamp      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type PivotCurrency struct {
	ID         int32
	CurrencyID pgtype.Int4
	Priority   int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type RateSubscription struct {
	ID               int32
	UserID           pgtype.Int4
	BaseCurrencyID   pgtype.Int4
	TargetCurrencyID pgtype.Int4
	PivotCurrencyID  pgtype.Int4
	Threshold        pgtype.Numeric
	NotificationSent pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID        int32
	Email     string
	CreatedAt pgtype.Timestamptz
}
