// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: q_currencies.sql

package database

import (
	"context"
)

const getCurrencyIdByCode = `-- name: GetCurrencyIdByCode :one
SELECT id FROM currencies WHERE code = $1
`

func (q *Queries) GetCurrencyIdByCode(ctx context.Context, code string) (int32, error) {
	row := q.db.QueryRow(ctx, getCurrencyIdByCode, code)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPivotIdByCurrencyId = `-- name: GetPivotIdByCurrencyId :one
SELECT id FROM pivot_currencies WHERE currency_id = $1
`

func (q *Queries) GetPivotIdByCurrencyId(ctx context.Context, currencyID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getPivotIdByCurrencyId, currencyID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertCurrency = `-- name: InsertCurrency :exec
INSERT INTO currencies (code, name, decimal_places, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT(code) DO UPDATE 
SET name = EXCLUDED.name, decimal_places = EXCLUDED.decimal_places, updated_at = NOW()
`

type InsertCurrencyParams struct {
	Code          string
	Name          string
	DecimalPlaces int32
}

func (q *Queries) InsertCurrency(ctx context.Context, arg InsertCurrencyParams) error {
	_, err := q.db.Exec(ctx, insertCurrency, arg.Code, arg.Name, arg.DecimalPlaces)
	return err
}

const insertPivotCurrency = `-- name: InsertPivotCurrency :exec
INSERT INTO pivot_currencies (currency_id, priority, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (currency_id) DO UPDATE
SET priority = EXCLUDED.priority, updated_at = NOW()
`

type InsertPivotCurrencyParams struct {
	CurrencyID int32
	Priority   int32
}

func (q *Queries) InsertPivotCurrency(ctx context.Context, arg InsertPivotCurrencyParams) error {
	_, err := q.db.Exec(ctx, insertPivotCurrency, arg.CurrencyID, arg.Priority)
	return err
}
