// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: q_exchange_rate_history.sql

package database

import (
	"context"
	"time"
)

const insertExchangeRateHistory = `-- name: InsertExchangeRateHistory :exec

INSERT INTO exchange_rate_history(base_currency_id, currency_id, exchange_rate, timestamp)
VALUES ($1, $2, $3, $4)
`

type InsertExchangeRateHistoryParams struct {
	BaseCurrencyID int32
	CurrencyID     int32
	ExchangeRate   float64
	Timestamp      time.Time
}

func (q *Queries) InsertExchangeRateHistory(ctx context.Context, arg InsertExchangeRateHistoryParams) error {
	_, err := q.db.Exec(ctx, insertExchangeRateHistory,
		arg.BaseCurrencyID,
		arg.CurrencyID,
		arg.ExchangeRate,
		arg.Timestamp,
	)
	return err
}
