// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: q_exchange_rate_history.sql

package database

import (
	"context"
)

const insertExchangeRateHistory = `-- name: InsertExchangeRateHistory :exec

INSERT INTO exchange_rate_history(base_currency_id, currency_id, exchange_rate, timestamp, created_at)
VALUES (
    (SELECT id FROM currencies c WHERE $1 = c.code),
    (SELECT id FROM currencies c WHERE $2 = c.code),
    $3,
    NOW(),
    NOW()
)
`

type InsertExchangeRateHistoryParams struct {
	BaseCurrencyCode   string
	TargetCurrencyCode string
	ExchangeRate       float64
}

func (q *Queries) InsertExchangeRateHistory(ctx context.Context, arg InsertExchangeRateHistoryParams) error {
	_, err := q.db.Exec(ctx, insertExchangeRateHistory, arg.BaseCurrencyCode, arg.TargetCurrencyCode, arg.ExchangeRate)
	return err
}
